variable "environment" {}
variable "product" {}
variable "db_username" {}
variable "db_password" {}
variable "db_host" {}
variable "region" {}
variable "live_in_security_group" {}
variable "vpc_subnets" {}
variable "vpc_id" {}