variable "environment" {}
variable "product" {}
variable "db_username" {}
variable "db_password" {}
variable "region" {}
variable "vpc_id" {}
variable "ip_address" {}
variable "vpc_subnets" {}
variable "allow_access_to_security_group_id" {}